### ISSUE TITLE
Vulkan Driver update

### ISSUE THREAD

**Issue by cruzadern** [Fcharan/Wine-Hangover-Patched#4]
I noticed that you have the same graphics accelerator as me (Mali g610), but you have the Vulcan v38.1 driver installed, and I only have v32.1

if you updated the driver manually, will you be able to make an instruction?

**Comment by Fcharan** [comment]
I didn't update anything it depends on your vendor

**Comment by cruzadern** [comment]
will you be able to write a smartphone model that was in the tests? I want to download its firmware and try to extract the vulkan driver from the firmware and replace it with my smartphone.
but there is a difference in graphics accelerators, you have a g610 mc4, I have an mc6.

**Comment by cruzadern** [comment]
> I didn't update anything it depends on your vendor

will you be able to write a smartphone model that was in the tests? I want to download its firmware and try to extract the vulkan driver from the firmware and replace it with my smartphone.
but there is a difference in graphics accelerators, you have a g610 mc4, I have an mc6.
